export * from './personnels-detail.component'
export * from './personnels.component'
export * from './personnels.module'
export * from './personnels.route'
export * from './personnel.service'
export * from './personnels.model'
export * from './personnelRecord.model'