export * from './represantant-legal.module'
export * from './representant-legal-detail.component'
export * from './representant-legal.component'
export * from './representant-legal.route'
export * from './representant-legal.service'
export * from './enfant.model'
export * from './representant-legal.model'
export * from './representantRecord.model'
